dependencies:
  # -<organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env

wallet :
  from_key : ${PRIVATE_KEY}
networks:
  rinkeby:
    eth_usd_priceFeed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: true
  development:
    verify: false
  mainnet-fork-dev:
      verify: false

  ganache:
    verify: false
